spring:
  kafka:
    bootstrap-servers:
      - 34.90.124.7:9092
      - 34.90.124.7:9093
      - 34.90.124.7:9094
    template:
      default-topic: alpha-service-topic
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
  application:
    name: alpha-service

server:
  port: 8083